export { AboutComponent } from './about/about.component';
export { TileComponent } from './tile/tile.component';
export { ContactComponent } from './contact/contact.component';
export { LoginComponent } from './login/login.component';
export { ErrorPageComponent } from './error-page/error-page.component';
export { HeaderComponent } from './header/header.component';
export { NavMenuComponent } from './nav-menu/nav-menu.component';
export { HomeComponent } from './home/home.component';
export { SiteSettingsComponent } from './site-settings/site-settings.component';
